CREATE TABLE document_retrieval_artifact (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '检索派生对象清单主键ID',
    tenant_id BIGINT NOT NULL COMMENT '所属租户ID，逻辑外键',
    document_version_id BIGINT NOT NULL COMMENT '所属不可变文档版本ID，唯一',
    canonical_artifact_id BIGINT NOT NULL COMMENT '生成输入对应的canonical清单ID',
    schema_version INT UNSIGNED NOT NULL COMMENT 'retrieval JSONL结构版本',
    chat_provider VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '检索卡供应商，第一版DEEPSEEK',
    chat_model VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '检索卡生成模型标识',
    chat_prompt_version VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '检索卡提示词版本',
    thinking_mode VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '检索卡思考模式，第一版DISABLED',
    embedding_provider VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '向量供应商，第一版ALIBABA_MODEL_STUDIO',
    embedding_model VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '导航向量模型标识',
    embedding_dimension INT UNSIGNED NOT NULL COMMENT '导航向量维数',
    embedding_template_version VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '导航文本模板版本',
    generation_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '输入和生成配置指纹SHA-256',
    retrieval_bucket VARCHAR(63) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '检索对象所在S3兼容Bucket',
    retrieval_object_key VARCHAR(1024) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '不可变retrieval JSONL对象Key',
    retrieval_size_bytes BIGINT NOT NULL COMMENT 'retrieval JSONL对象字节数',
    retrieval_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'retrieval JSONL对象SHA-256',
    semantic_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '稳定语义字段序列SHA-256',
    vector_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '稳定向量原始字节序列SHA-256',
    profile_count INT UNSIGNED NOT NULL COMMENT '文档级检索卡数量，第一版固定为1',
    node_count INT UNSIGNED NOT NULL COMMENT '真实非根标题检索卡数量',
    vector_count INT UNSIGNED NOT NULL COMMENT '导航向量数量，等于profile加node数量',
    created_at DATETIME(6) NOT NULL COMMENT '检索对象清单创建时间，UTC',
    updated_at DATETIME(6) NOT NULL COMMENT '清单最后更新时间，第一版等于创建时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_document_retrieval_artifact_version (document_version_id),
    UNIQUE KEY uk_document_retrieval_artifact_object (retrieval_bucket, retrieval_object_key),
    KEY idx_document_retrieval_artifact_tenant_version (tenant_id, document_version_id),
    KEY idx_document_retrieval_artifact_canonical (canonical_artifact_id)
) ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;
